<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FabioCumulativeTradeRecorder</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\Observation\CumulativeTradeObservationRecorder.cs" Link="CumulativeTradeObservationRecorder.cs" />
  </ItemGroup>
</Project>
