<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FabioDataBridge</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\Observation\DataBridge.cs" Link="DataBridge.cs" />
    <Compile Include="..\..\Observation\RegoleDeiLivelli.cs" Link="RegoleDeiLivelli.cs" />
    <Compile Include="..\..\Observation\IlRegimeELaVelocita.cs" Link="IlRegimeELaVelocita.cs" />
  </ItemGroup>
</Project>
